Add support for configurable node groups
charmed-kubernetes/autoscaler pull request #1
Opened 2022-02-23 17:05 UTC by Cynerva

This PR makes it possible to specify node group information when running cluster-autoscaler:

```
./cluster-autoscaler-amd64 --cloud-provider=juju --nodes 3:10:kubernetes-worker
```

where 3 is the min size, 10 is the max size, and kubernetes-worker is the application name. The `--nodes` option can be specified multiple time to support multiple node groups.

This needs further work. The application name is ignored for now, and there are still some hard-coded assumptions that there is only 1 node group. I'm working on it.

2022-02-25 15:22 UTC, Cynerva commented
This is ready for review. To run the cluster-autoscaler with these changes, include the `--nodes 1:3:<model>,<application>` option specified one or more times. For example:

```
./cluster-autoscaler-amd64 -v=5 --kubeconfig=/home/gkk/.kube/config --cloud-provider=juju --max-node-provision-time 30m0s --scale-down-unneeded-time=5m0s --nodes 1:3:test,kubernetes-worker
```

I've split this up into two commits. The first commit is just reformatting with `gofmt -w *`. The second commit has the functional changes. Consider reading the second commit specifically if you want to understand the functional changes without all the reformatting noise.

2022-02-28 18:34 UTC, addyess commented
> This is ready for review. To run the cluster-autoscaler with these changes, include the `--nodes 1:3:<model>,<application>` option specified one or more times. For example:
> 
> ```
> ./cluster-autoscaler-amd64 -v=5 --kubeconfig=$HOME/.kube/config --cloud-provider=juju --max-node-provision-time 30m0s --scale-down-unneeded-time=5m0s --nodes 1:3:test,kubernetes-worker
> ```
> 
> I've split this up into two commits. The first commit is just reformatting with `gofmt -w *`. The second commit has the functional changes. Consider reading the second commit specifically if you want to understand the functional changes without all the reformatting noise.

@Cynerva just confirming this isn't a typo:
`1:3:test,kubernetes-worker` not `1:3:test:kubernetes-worker`.  I'd expected colon separators for everything here -- and designed the charm around colon separators.  should i update or can you?


secondarily.  does this have to be a "name" or can it be model uuid?

```bash
juju status -m 3523dd89-c23e-4a7b-84f1-9d8f807b0c09
```

works just fine for me.

2022-02-28 18:51 UTC, addyess requested changes
Proposing a colon-delimiter between model and app

2022-02-28 18:51 UTC, addyess commented on cluster-autoscaler/cloudprovider/juju/juju_cloud_provider.go
> +		nodeGroupSpec, err := dynamic.SpecFromString(nodeGroupSpecString, scaleToZeroSupported)
Ahh, i see [this](https://github.com/charmed-kubernetes/autoscaler/blob/master/cluster-autoscaler/config/dynamic/node_group_spec.go#L38) splits a string 3 times with ':' probably leading to why you chose `min:max:node-group`  where `node-group` is split again with a `,`

2022-02-28 18:51 UTC, addyess commented on cluster-autoscaler/cloudprovider/juju/juju_cloud_provider.go
> +		nodeGroupSpec, err := dynamic.SpecFromString(nodeGroupSpecString, scaleToZeroSupported)
However `strings.SplitN(nodeGroupSpecString, 3)` will only split three times -- leaving the rest of the string unsplit.  
if you'd be willing to entertain that 3rd string token here can be FULL of colons (`:`) then i'd propose we continue using it as a delimiter for `<model>:<app>`   i don't think `:` can be used in the name of a juju application

2022-02-28 18:53 UTC, Cynerva commented
> @Cynerva just confirming this isn't a typo:
1:3:test,kubernetes-worker not 1:3:test:kubernetes-worker. I'd expected colon separators for everything here -- and designed the charm around colon separators. should i update or can you?

Yup, not a typo. I split on `,` because while the [SpecFromString](https://github.com/charmed-kubernetes/autoscaler/blob/6508db18d2099bec292387aebe442da27d10b958/cluster-autoscaler/config/dynamic/node_group_spec.go#L39-L42) function *does* allow for more than 3 `:`-separated fields, it wasn't clear to me that this is intentional behavior.

That said, I just searched and I see there is precedent in the Hetzner cloud provider code for using more than 3 `:`-separated fields. See the [Hetzner cloud provider README](https://github.com/charmed-kubernetes/autoscaler/blob/6508db18d2099bec292387aebe442da27d10b958/cluster-autoscaler/cloudprovider/hetzner/README.md). So we may as well do the same. I'll update this PR to separate on `:` instead.

2022-02-28 18:55 UTC, addyess approved these changes
LGTM

2022-02-28 18:55 UTC, merged

2022-02-28 18:57 UTC, Cynerva commented
> secondarily. does this have to be a "name" or can it be model uuid?

UUID should work too