Testability
charmed-kubernetes/autoscaler pull request #8
Opened 2022-03-31 17:46 UTC by stonepreston

Adds unit tests for the manager component of the juju autoscaler. This involved refactoring the code to be more testable via dependency injection and interfaces to facilitate mocking. This PR also adds a github workflow to run the tests, and a readme for the juju provider.

2022-03-31 18:14 UTC, addyess commented on cluster-autoscaler/cloudprovider/juju/juju_cloud_provider.go
> +}
awesome.  thank you for making them lowercase!

2022-03-31 18:17 UTC, addyess approved these changes
Let's be honest, i'm not a go expert.  But i can TOTALLY read this code and it's pretty clear what's going on.  Amazing improvement from my point of view

2022-03-31 20:38 UTC, Cynerva requested changes
Nice work. I just have one concern with the GitHub workflow file.

2022-03-31 20:38 UTC, Cynerva commented on cluster-autoscaler/.github/workflows/test.yaml
> +name: "Build"
I think this file needs to be moved to the root of the repo, from

```
cluster-autoscaler/.github/workflows/test.yaml
```

to

```
.github/workflows/test.yaml
```

per GitHub documentation here: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#about-workflow-triggers

> GitHub searches the `.github/workflows` directory in your repository for workflow files that are present in the associated commit SHA or Git ref of the event.

2022-03-31 21:31 UTC, stonepreston commented on cluster-autoscaler/.github/workflows/test.yaml
> +name: "Build"
Alright good catch. Ive moved the workflow up, I also disabled the other upstream workflows via the github UI. Unfortunately I was testing locally using go 1.17 and things were working fine. The go mod file specified 1.16 though. The tests were failing when running on GH using 1.16, so had to update go.mod to 1.17 which changed a bunch of vendored packages. Tests are passing now

2022-04-01 13:34 UTC, Cynerva approved these changes

2022-04-01 13:35 UTC, merged